apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      labels:
        app: blue
        canary: blue-green
    spec:
      containers:
      - name: bear
        image: supergiantkir/animals:bear
        ports:
        - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: green
  template:
    metadata:
      labels:
        app: green
        canary: blue-green
    spec:
      containers:
      - name: hear
        image: supergiantkir/animals:hear
        ports:
        - containerPort: 80
        
  #kubectl apply -f svc-animals.yaml
  #kubectl delete all --all

