kind: Service
apiVersion: v1
metadata:
  name: spring-music
  labels:
    app: spring-music
spec:
  selector:
    app:
  ports:
  - name: http-web
    protocol: TCP
    port: 80
    targetPort: 8080
    type: LoadBalancer
