apiVersion: v1
kind: Service
metadata:
  labels:
    deploy: blue-green
  name: blue-green-deployment
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    canary: blue-green
  type: LoadBalancer
  
  #kubectl apply -f svc-animals.yaml
  #kubectl delete all --all

