apiVersion: v1
kind: Service
metadata:
  labels:
    deploy: hear-bear
  name: hear-bear-deployment
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    canary: hear-bear
  type: LoadBalancer
